sudo: required
services:
  - docker

before_install:
  - docker build -t erimerdal/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true erimerdal/react-test npm test

after_success:
  - docker build -t erimerdal/multi-client ./client
  - docker build -t erimerdal/multi-nginx ./nginx
  - docker build -t erimerdal/multi-server ./server
  - docker build -t erimerdal/multi-worker ./worker
